In [3]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn import linear_model
import statsmodels.formula.api as smf

In [5]:
pwd

'/Users/mauroaz/Documents/Git_General'

In [7]:
import os
os.chdir("/Users/mauroaz/Documents/Git_General/breast-cancer")

In [8]:
cancer = pd.read_csv("breast-cancer-wisconsin.data")

In [21]:
pwd

'/Users/mauroaz/Documents/Git_General/breast-cancer'

In [22]:
cancer.columns = ['sample_code_num', 'clump_thickness', 'uniformity_cell_size', 'uniformity_cell_shape',
                              'marginal_adhesion', 'single_epithelial_cell_size', 'bare_nuclei', 'bland_chromatin',
                              'normal_nucleoli', 'mitoses', 'target' ]

In [12]:
cancer.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 698 entries, 0 to 697
Data columns (total 11 columns):
1000025    698 non-null int64
5          698 non-null int64
1          698 non-null int64
1.1        698 non-null int64
1.2        698 non-null int64
2          698 non-null int64
1.3        698 non-null object
3          698 non-null int64
1.4        698 non-null int64
1.5        698 non-null int64
2.1        698 non-null int64
dtypes: int64(10), object(1)
memory usage: 60.1+ KB

In [24]:
cancer.describe()

,sample_code_num,clump_thickness,uniformity_cell_size,uniformity_cell_shape,marginal_adhesion,single_epithelial_cell_size,bland_chromatin,normal_nucleoli,mitoses,target
count,6.980000e+02,698.000000,698.000000,698.000000,698.000000,698.000000,698.000000,698.000000,698.000000,698.000000
mean,1.071807e+06,4.416905,3.137536,3.210602,2.809456,3.217765,3.438395,2.869628,1.590258,2.690544
std,6.175323e+05,2.817673,3.052575,2.972867,2.856606,2.215408,2.440056,3.055004,1.716162,0.951596
min,6.163400e+04,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,2.000000
25%,8.702582e+05,2.000000,1.000000,1.000000,1.000000,2.000000,2.000000,1.000000,1.000000,2.000000
50%,1.171710e+06,4.000000,1.000000,1.000000,1.000000,2.000000,3.000000,1.000000,1.000000,2.000000
75%,1.238354e+06,6.000000,5.000000,5.000000,4.000000,4.000000,5.000000,4.000000,1.000000,4.000000
max,1.345435e+07,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,4.000000

In [23]:
cancer.head()

,sample_code_num,clump_thickness,uniformity_cell_size,uniformity_cell_shape,marginal_adhesion,single_epithelial_cell_size,bare_nuclei,bland_chromatin,normal_nucleoli,mitoses,target
0,1002945,5,4,4,5,7,10,3,2,1,2
1,1015425,3,1,1,1,2,2,3,1,1,2
2,1016277,6,8,8,1,3,4,3,7,1,2
3,1017023,4,1,1,3,2,1,3,1,1,2
4,1017122,8,10,10,8,7,10,9,7,1,4

In [36]:
list(cancer.columns)

['sample_code_num',
 'clump_thickness',
 'uniformity_cell_size',
 'uniformity_cell_shape',
 'marginal_adhesion',
 'single_epithelial_cell_size',
 'bare_nuclei',
 'bland_chromatin',
 'normal_nucleoli',
 'mitoses',
 'target']

In [26]:
cancer.tail()

,sample_code_num,clump_thickness,uniformity_cell_size,uniformity_cell_shape,marginal_adhesion,single_epithelial_cell_size,bare_nuclei,bland_chromatin,normal_nucleoli,mitoses,target
693,776715,3,1,1,1,3,2,1,1,1,2
694,841769,2,1,1,1,2,1,1,1,1,2
695,888820,5,10,10,3,7,3,8,10,2,4
696,897471,4,8,6,4,3,4,10,6,1,4
697,897471,4,8,8,5,4,5,10,4,1,4

In [30]:
cancer['target'] = cancer['target'].apply(lambda x: 0 if x == 2 else 1)

In [48]:
fitted_model = smf.logit(formula= 'target ~ sample_code_num + clump_thickness + uniformity_cell_size + uniformity_cell_shape + marginal_adhesion + single_epithelial_cell_size + bland_chromatin + normal_nucleoli + mitoses + bare_nuclei',
data=cancer).fit()
fitted_model.summary()

Warning: Maximum number of iterations has been exceeded.
         Current function value: 0.072664
         Iterations: 35

/Users/mauroaz/miniconda3/lib/python3.7/site-packages/statsmodels/base/model.py:512: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals
  "Check mle_retvals", ConvergenceWarning)

<class 'statsmodels.iolib.summary.Summary'>
"""
                           Logit Regression Results
==============================================================================
Dep. Variable:                 target   No. Observations:                  698
Model:                          Logit   Df Residuals:                      678
Method:                           MLE   Df Model:                           19
Date:                Wed, 20 Nov 2019   Pseudo R-squ.:                  0.8872
Time:                        14:51:33   Log-Likelihood:                -50.720
converged:                      False   LL-Null:                       -449.84
Covariance Type:            nonrobust   LLR p-value:                5.082e-157
===============================================================================================
                                  coef    std err          z      P>|z|      [0.025      0.975]
-----------------------------------------------------------------------------------------------
Intercept                     -10.1969      1.442     -7.071      0.000     -13.023      -7.371
bare_nuclei[T.10]               3.6665      0.932      3.935      0.000       1.840       5.493
bare_nuclei[T.2]                0.7551      1.065      0.709      0.478      -1.331       2.842
bare_nuclei[T.3]                2.4763      0.958      2.585      0.010       0.599       4.354
bare_nuclei[T.4]                3.1698      1.121      2.828      0.005       0.973       5.367
bare_nuclei[T.5]                2.0893      1.101      1.898      0.058      -0.068       4.247
bare_nuclei[T.6]               24.7256   6.35e+04      0.000      1.000   -1.25e+05    1.25e+05
bare_nuclei[T.7]                2.0781      1.540      1.349      0.177      -0.941       5.097
bare_nuclei[T.8]                1.8005      1.183      1.522      0.128      -0.519       4.120
bare_nuclei[T.9]                8.6750     21.734      0.399      0.690     -33.923      51.273
bare_nuclei[T.?]               -1.7141      1.510     -1.135      0.256      -4.674       1.246
sample_code_num              1.422e-07   5.47e-07      0.260      0.795    -9.3e-07    1.21e-06
clump_thickness                 0.4590      0.158      2.901      0.004       0.149       0.769
uniformity_cell_size           -0.0983      0.208     -0.472      0.637      -0.506       0.310
uniformity_cell_shape           0.5109      0.248      2.059      0.040       0.025       0.997
marginal_adhesion               0.2265      0.117      1.940      0.052      -0.002       0.455
single_epithelial_cell_size     0.1281      0.162      0.792      0.428      -0.189       0.445
bland_chromatin                 0.5489      0.180      3.042      0.002       0.195       0.902
normal_nucleoli                 0.1442      0.117      1.230      0.219      -0.086       0.374
mitoses                         0.4211      0.307      1.370      0.171      -0.181       1.023
===============================================================================================
"""

In [49]:
fitted_model = smf.logit(formula= 'target ~ sample_code_num + clump_thickness + uniformity_cell_size + uniformity_cell_shape + marginal_adhesion + single_epithelial_cell_size + bland_chromatin + normal_nucleoli + mitoses',
data=cancer).fit()
fitted_model.summary()

Optimization terminated successfully.
         Current function value: 0.100339
         Iterations 9

<class 'statsmodels.iolib.summary.Summary'>
"""
                           Logit Regression Results
==============================================================================
Dep. Variable:                 target   No. Observations:                  698
Model:                          Logit   Df Residuals:                      688
Method:                           MLE   Df Model:                            9
Date:                Wed, 20 Nov 2019   Pseudo R-squ.:                  0.8443
Time:                        14:52:03   Log-Likelihood:                -70.037
converged:                       True   LL-Null:                       -449.84
Covariance Type:            nonrobust   LLR p-value:                1.048e-157
===============================================================================================
                                  coef    std err          z      P>|z|      [0.025      0.975]
-----------------------------------------------------------------------------------------------
Intercept                      -9.3221      1.310     -7.119      0.000     -11.889      -6.755
sample_code_num             -5.557e-07   7.78e-07     -0.714      0.475   -2.08e-06     9.7e-07
clump_thickness                 0.5780      0.119      4.856      0.000       0.345       0.811
uniformity_cell_size           -0.0074      0.177     -0.042      0.966      -0.353       0.339
uniformity_cell_shape           0.5537      0.194      2.857      0.004       0.174       0.934
marginal_adhesion               0.3114      0.101      3.074      0.002       0.113       0.510
single_epithelial_cell_size     0.1425      0.141      1.008      0.314      -0.135       0.420
bland_chromatin                 0.5658      0.147      3.853      0.000       0.278       0.854
normal_nucleoli                 0.1175      0.099      1.188      0.235      -0.076       0.311
mitoses                         0.6063      0.313      1.936      0.053      -0.007       1.220
===============================================================================================
"""

In [50]:
fitted_model = smf.logit(formula= 'target ~ sample_code_num + clump_thickness + uniformity_cell_shape + marginal_adhesion + single_epithelial_cell_size + bland_chromatin + normal_nucleoli + mitoses',
data=cancer).fit()
fitted_model.summary()

Optimization terminated successfully.
         Current function value: 0.100341
         Iterations 9

<class 'statsmodels.iolib.summary.Summary'>
"""
                           Logit Regression Results
==============================================================================
Dep. Variable:                 target   No. Observations:                  698
Model:                          Logit   Df Residuals:                      689
Method:                           MLE   Df Model:                            8
Date:                Wed, 20 Nov 2019   Pseudo R-squ.:                  0.8443
Time:                        14:54:59   Log-Likelihood:                -70.038
converged:                       True   LL-Null:                       -449.84
Covariance Type:            nonrobust   LLR p-value:                1.042e-158
===============================================================================================
                                  coef    std err          z      P>|z|      [0.025      0.975]
-----------------------------------------------------------------------------------------------
Intercept                      -9.3116      1.285     -7.247      0.000     -11.830      -6.793
sample_code_num             -5.567e-07   7.78e-07     -0.716      0.474   -2.08e-06    9.68e-07
clump_thickness                 0.5772      0.117      4.915      0.000       0.347       0.807
uniformity_cell_shape           0.5487      0.153      3.579      0.000       0.248       0.849
marginal_adhesion               0.3104      0.098      3.158      0.002       0.118       0.503
single_epithelial_cell_size     0.1418      0.140      1.010      0.312      -0.133       0.417
bland_chromatin                 0.5649      0.145      3.885      0.000       0.280       0.850
normal_nucleoli                 0.1170      0.098      1.189      0.234      -0.076       0.310
mitoses                         0.6048      0.311      1.942      0.052      -0.006       1.215
===============================================================================================
"""

In [55]:
cancer["bare_nuclei3"] = cancer["bare_nuclei"].astype(int)==3
cancer.head(50)

ValueError: invalid literal for int() with base 10: '?'

In [58]:
cancer_cleaned=cancer[cancer['bare_nuclei'] !='?']

In [59]:
cancer_cleaned["bare_nuclei3"] = cancer_cleaned["bare_nuclei"].astype(int)==3
cancer_cleaned.head(50)

/Users/mauroaz/miniconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.

,sample_code_num,clump_thickness,uniformity_cell_size,uniformity_cell_shape,marginal_adhesion,single_epithelial_cell_size,bare_nuclei,bland_chromatin,normal_nucleoli,mitoses,target,bare_nuclei3
0,1002945,5,4,4,5,7,10,3,2,1,0,False
1,1015425,3,1,1,1,2,2,3,1,1,0,False
2,1016277,6,8,8,1,3,4,3,7,1,0,False
3,1017023,4,1,1,3,2,1,3,1,1,0,False
4,1017122,8,10,10,8,7,10,9,7,1,1,False
5,1018099,1,1,1,1,2,10,3,1,1,0,False
6,1018561,2,1,2,1,2,1,3,1,1,0,False
7,1033078,2,1,1,1,2,1,1,1,5,0,False
8,1033078,4,2,1,1,2,1,2,1,1,0,False
9,1035283,1,1,1,1,1,1,3,1,1,0,False
10,1036172,2,1,1,1,2,1,2,1,1,0,False
11,1041801,5,3,3,3,2,3,4,4,1,1,True
12,1043999,1,1,1,1,2,3,3,1,1,0,True
13,1044572,8,7,5,10,7,9,5,5,4,1,False
14,1047630,7,4,6,4,6,1,4,3,1,1,False
15,1048672,4,1,1,1,2,1,2,1,1,0,False
16,1049815,4,1,1,1,2,1,3,1,1,0,False
17,1050670,10,7,7,6,4,10,4,1,2,1,False
18,1050718,6,1,1,1,2,1,3,1,1,0,False
19,1054590,7,3,2,10,5,10,5,4,4,1,False
20,1054593,10,5,5,3,6,7,7,10,1,1,False
21,1056784,3,1,1,1,2,1,2,1,1,0,False
23,1059552,1,1,1,1,2,1,3,1,1,0,False
24,1065726,5,2,3,4,2,7,3,6,1,1,False
25,1066373,3,2,1,1,1,1,2,1,1,0,False
26,1066979,5,1,1,1,2,1,2,1,1,0,False
27,1067444,2,1,1,1,2,1,2,1,1,0,False
28,1070935,1,1,3,1,2,1,1,1,1,0,False
29,1070935,3,1,1,1,1,1,2,1,1,0,False
30,1071760,2,1,1,1,2,1,3,1,1,0,False
31,1072179,10,7,7,3,8,5,7,4,3,1,False
32,1074610,2,1,1,2,2,1,3,1,1,0,False
33,1075123,3,1,2,1,2,1,2,1,1,0,False
34,1079304,2,1,1,1,2,1,2,1,1,0,False
35,1080185,10,10,10,8,6,1,8,9,1,1,False
36,1081791,6,2,1,1,1,1,7,1,1,0,False
37,1084584,5,4,4,9,2,10,5,6,1,1,False
38,1091262,2,5,3,3,6,7,7,5,1,1,False
40,1099510,10,4,3,1,3,3,6,5,2,1,True
41,1100524,6,10,10,2,8,10,7,3,3,1,False
42,1102573,5,6,5,6,10,1,3,1,1,1,False
43,1103608,10,10,10,4,8,1,8,10,1,1,False
44,1103722,1,1,1,1,2,1,2,1,2,0,False
45,1105257,3,7,7,4,4,9,4,8,1,1,False
46,1105524,1,1,1,1,2,1,2,1,1,0,False
47,1106095,4,1,1,3,2,1,3,1,1,0,False
48,1106829,7,8,7,2,4,8,3,8,2,1,False
49,1108370,9,5,8,1,2,3,2,1,5,1,True
50,1108449,5,3,3,4,2,4,3,4,1,1,False
51,1110102,10,3,6,2,3,5,4,10,2,1,False

In [61]:
fitted_model = smf.logit(formula= 'target ~ sample_code_num + clump_thickness + uniformity_cell_size + uniformity_cell_shape + marginal_adhesion + single_epithelial_cell_size + bland_chromatin + normal_nucleoli + mitoses + bare_nuclei3',
data=cancer_cleaned).fit()
fitted_model.summary()

Optimization terminated successfully.
         Current function value: 0.088463
         Iterations 10

<class 'statsmodels.iolib.summary.Summary'>
"""
                           Logit Regression Results
==============================================================================
Dep. Variable:                 target   No. Observations:                  682
Model:                          Logit   Df Residuals:                      671
Method:                           MLE   Df Model:                           10
Date:                Wed, 20 Nov 2019   Pseudo R-squ.:                  0.8634
Time:                        16:36:01   Log-Likelihood:                -60.332
converged:                       True   LL-Null:                       -441.74
Covariance Type:            nonrobust   LLR p-value:                2.017e-157
===============================================================================================
                                  coef    std err          z      P>|z|      [0.025      0.975]
-----------------------------------------------------------------------------------------------
Intercept                      -9.7472      1.487     -6.554      0.000     -12.662      -6.832
bare_nuclei3[T.True]            0.7600      0.920      0.826      0.409      -1.043       2.563
sample_code_num             -7.149e-07   8.63e-07     -0.828      0.408   -2.41e-06    9.77e-07
clump_thickness                 0.6084      0.134      4.537      0.000       0.346       0.871
uniformity_cell_size           -0.0097      0.200     -0.048      0.961      -0.401       0.382
uniformity_cell_shape           0.5441      0.217      2.511      0.012       0.119       0.969
marginal_adhesion               0.3772      0.112      3.357      0.001       0.157       0.597
single_epithelial_cell_size     0.1836      0.153      1.201      0.230      -0.116       0.483
bland_chromatin                 0.6010      0.162      3.702      0.000       0.283       0.919
normal_nucleoli                 0.1692      0.109      1.548      0.122      -0.045       0.383
mitoses                         0.5259      0.371      1.419      0.156      -0.201       1.252
===============================================================================================
"""